### ISSUE TITLE
Error while running import_microbekg.ipynb

### ISSUE THREAD

**Issue by wasimaftab** [dgg32/kg_microbe_biocypher_semspect#1]
The following error comes from this line: `driver.write_nodes(ncbitaxon_generator())`

`ValueError:` Node OrganismTaxon not found in ontology, but also has no inheritance definition. Please check your schema for spelling errors or a missing `is_a` definition.

**Comment by dgg32** [comment]
It seems BioCypher has changed dramatically in the current version. It changes its class, ontology etc. Let me take a look.

**Comment by dgg32** [comment]
@wasimaftab Hi. I have pushed a new version of the code. It solves all errors brought by the new version of BioCypher and imported the data into my Neo4j. I will update my article tomorrow.

**Comment by dgg32** [comment]
@wasimaftab Hi. I have pushed a new version of the code. It solves all errors brought by the new version of BioCypher and imported the data into my Neo4j. I will update my article tomorrow.
